/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laskarit.ui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import laskarit.muotoilu.Esitys;
import laskarit.tehtavat.Tehtava;
import laskarit.tehtavat.Tehtavatehdas;

/**
 * Pelipaneli huolehtii pelin käyttöliittymän pyörittämisestä.
 * @author simo
 */
public class Pelipaneli extends javax.swing.JPanel {

    private final Pelikuuntelija kuuntelija;
    private final Tehtavatehdas peli;
    private Tehtava tehtava;

    private final Timer timerPalaute;

    /**
     * Luo pelipanelin
     * @param ikkuna Ikkuna, jossa pelipaneli sijaitsee.
     * @param peli Tehtavatehdas, josta uudet kysymykset pyydetään.
     */
    public Pelipaneli(Pelikuuntelija kuuntelija, Tehtavatehdas peli) {
        this.kuuntelija = kuuntelija;
        this.peli = peli;
        initComponents();
        labelVaaraVastaus.setVisible(false);
        labelOikeaVastaus.setVisible(false);
        timerPalaute = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                poistaPalaute();
            }

        });
        timerPalaute.setRepeats(false);

        uusiKysymys();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ylapaneli = new javax.swing.JPanel();
        jbPalaa = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        kysymyspaneli = new javax.swing.JPanel();
        labelKysymys = new javax.swing.JLabel();
        panelVaaraVastaus = new javax.swing.JPanel();
        labelVaaraVastaus = new javax.swing.JLabel();
        labelOikeaVastaus = new javax.swing.JLabel();
        vastauspaneli = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel1 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        tfVastaus = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        ylapaneli.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 1, 2, 1));
        ylapaneli.setMinimumSize(new java.awt.Dimension(150, 25));
        ylapaneli.setOpaque(false);
        ylapaneli.setLayout(new javax.swing.BoxLayout(ylapaneli, javax.swing.BoxLayout.LINE_AXIS));

        jbPalaa.setBackground(new java.awt.Color(255, 255, 255));
        jbPalaa.setText("Takaisin valintaan");
        jbPalaa.setFocusable(false);
        jbPalaa.setRolloverEnabled(false);
        jbPalaa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPalaaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPalaaMouseExited(evt);
            }
        });
        jbPalaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalaaActionPerformed(evt);
            }
        });
        ylapaneli.add(jbPalaa);
        ylapaneli.add(filler5);

        add(ylapaneli);
        add(filler1);

        kysymyspaneli.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        kysymyspaneli.setOpaque(false);
        kysymyspaneli.setLayout(new javax.swing.BoxLayout(kysymyspaneli, javax.swing.BoxLayout.LINE_AXIS));

        labelKysymys.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelKysymys.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKysymys.setText("kysymys");
        labelKysymys.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        kysymyspaneli.add(labelKysymys);

        add(kysymyspaneli);

        panelVaaraVastaus.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        panelVaaraVastaus.setMinimumSize(new java.awt.Dimension(115, 50));
        panelVaaraVastaus.setName(""); // NOI18N
        panelVaaraVastaus.setOpaque(false);
        panelVaaraVastaus.setPreferredSize(new java.awt.Dimension(400, 50));
        panelVaaraVastaus.setLayout(new javax.swing.BoxLayout(panelVaaraVastaus, javax.swing.BoxLayout.LINE_AXIS));

        labelVaaraVastaus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelVaaraVastaus.setForeground(new java.awt.Color(255, 0, 0));
        labelVaaraVastaus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVaaraVastaus.setText("Väärä vastaus :(");
        labelVaaraVastaus.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelVaaraVastaus.add(labelVaaraVastaus);

        labelOikeaVastaus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelOikeaVastaus.setForeground(java.awt.Color.green);
        labelOikeaVastaus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOikeaVastaus.setText("Oikea vastaus :)");
        labelOikeaVastaus.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelVaaraVastaus.add(labelOikeaVastaus);

        add(panelVaaraVastaus);

        vastauspaneli.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 1, 2, 1));
        vastauspaneli.setMinimumSize(new java.awt.Dimension(150, 25));
        vastauspaneli.setOpaque(false);
        vastauspaneli.setLayout(new javax.swing.BoxLayout(vastauspaneli, javax.swing.BoxLayout.LINE_AXIS));
        vastauspaneli.add(filler3);

        jLabel1.setLabelFor(tfVastaus);
        jLabel1.setText("Vastaus");
        vastauspaneli.add(jLabel1);
        vastauspaneli.add(filler4);

        tfVastaus.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfVastaus.setMaximumSize(new java.awt.Dimension(100, 40));
        tfVastaus.setMinimumSize(new java.awt.Dimension(100, 20));
        tfVastaus.setPreferredSize(new java.awt.Dimension(100, 30));
        tfVastaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVastausActionPerformed(evt);
            }
        });
        vastauspaneli.add(tfVastaus);
        vastauspaneli.add(filler2);

        add(vastauspaneli);
    }// </editor-fold>//GEN-END:initComponents

    private void tfVastausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVastausActionPerformed
        String vastaus = tfVastaus.getText();
        if(!"".equals(vastaus)) {
            tfVastaus.setText("");
            vastausAnnettu(vastaus);
        }
    }//GEN-LAST:event_tfVastausActionPerformed

    private void jbPalaaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPalaaMouseEntered
        jbPalaa.setBackground(Color.GRAY);
    }//GEN-LAST:event_jbPalaaMouseEntered

    private void jbPalaaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPalaaMouseExited
        jbPalaa.setBackground(Color.WHITE);
    }//GEN-LAST:event_jbPalaaMouseExited

    private void jbPalaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalaaActionPerformed
        kuuntelija.peliPaattyi();
    }//GEN-LAST:event_jbPalaaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbPalaa;
    private javax.swing.JPanel kysymyspaneli;
    private javax.swing.JLabel labelKysymys;
    private javax.swing.JLabel labelOikeaVastaus;
    private javax.swing.JLabel labelVaaraVastaus;
    private javax.swing.JPanel panelVaaraVastaus;
    private javax.swing.JTextField tfVastaus;
    private javax.swing.JPanel vastauspaneli;
    private javax.swing.JPanel ylapaneli;
    // End of variables declaration//GEN-END:variables

    private void uusiKysymys() {
        tehtava = peli.annaTehtava();
        labelVaaraVastaus.setVisible(false);
        labelKysymys.setText("<html>" + tehtava.annaKysymys().toString(null) + "</html>");
    }

    private void vaaraVastaus() {
        palaute(false);
    }

    private void oikeaVastaus() {
        palaute(true);
        uusiKysymys();
    }

    private void vastausAnnettu(String vastaus) {
        if(tehtava.tarkistaVastaus(vastaus)) {
            oikeaVastaus();
        }
        else {
            vaaraVastaus();
        }

    }

    private void palaute(boolean oikein) {
        labelOikeaVastaus.setVisible(oikein);
        labelVaaraVastaus.setVisible(!oikein);
        timerPalaute.restart();
    }

    private void poistaPalaute() {
        labelOikeaVastaus.setVisible(false);
        labelVaaraVastaus.setVisible(false);
    }

    void aktivoi() {
        tfVastaus.requestFocus();
    }


}
