/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laskarit.ui;

import java.awt.BorderLayout;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import laskarit.tehtavat.KaikkiTehtavat;
import laskarit.tehtavat.Kertolaskarit;
import laskarit.tehtavat.Logaritmilaskarit;
import laskarit.tehtavat.Potenssilaskarit;
import laskarit.tehtavat.Tehtavatehdas;
import laskarit.tehtavat.ToisenAsteenYhtalo;
import laskarit.tehtavat.Yhteenlaskarit;

/**
 * Ohjelman graafisen käyttöliittymän pääikkuna.
 * 
 * @author simo
 */
public class PeliIkkuna extends javax.swing.JFrame {
    private final Pelivalinta[] pelit = new Pelivalinta[] {
        new Pelivalinta("Tosilaskarit", "Kaikenlaisia tehtäviä!", new KaikkiTehtavat()),
        new Pelivalinta("Yhteenlaskarit", "Helppoja yhteenlaskuharjoituksia", new Yhteenlaskarit(10)),
        new Pelivalinta("Vaikeat yhteenlaskarit", "Vaikeampia yhteenlaskuharjoituksia", new Yhteenlaskarit(1000)),
        new Pelivalinta("Kertolaskarit", "Helppoja kertolaskuharjoituksia", new Kertolaskarit(10)),
        new Pelivalinta("Vaikeat kertolaskarit", "Vaikeampia kertolaskuharjoituksia", new Kertolaskarit(100)),
        new Pelivalinta("Potenssilaskarit", "Helppoja potenssilaskuja", new Potenssilaskarit(5, 3)),
        new Pelivalinta("Logaritmilaskarit", "Helppoja potenssiyhtälöharjoituksia", new Logaritmilaskarit(5, 3)),
        new Pelivalinta("Laskarit^2", "Toisen asteen yhtälöiden harjoituksia", new ToisenAsteenYhtalo(10, true))
    };

    Valintapaneli<Pelivalinta> valintaPaneli;
    private Pelipaneli pelipaneli;

    /**
     * Creates new form PeliIkkuna
     */
    public PeliIkkuna() {
        initComponents();
        valintaPaneli = new Valintapaneli<>(pelit,
                new Valintakuuntelija<Pelivalinta>() {
                    @Override
                    public void valintaTehty(Pelivalinta valinta) {
                        PeliIkkuna.this.valintaTehty(valinta);
                    }
                });
        naytaValinta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vaihtuvaPaneli = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuPeli = new javax.swing.JMenu();
        menuItemLopeta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laskarit");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        vaihtuvaPaneli.setBackground(new java.awt.Color(255, 255, 255));
        vaihtuvaPaneli.setLayout(new java.awt.BorderLayout());
        getContentPane().add(vaihtuvaPaneli);

        menuPeli.setText("Peli");

        menuItemLopeta.setText("Lopeta");
        menuItemLopeta.setToolTipText("");
        menuItemLopeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLopetaActionPerformed(evt);
            }
        });
        menuPeli.add(menuItemLopeta);

        menuBar.add(menuPeli);

        setJMenuBar(menuBar);

        setBounds(0, 0, 532, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemLopetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLopetaActionPerformed
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_menuItemLopetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeliIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeliIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeliIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeliIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeliIkkuna().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemLopeta;
    private javax.swing.JMenu menuPeli;
    private javax.swing.JPanel vaihtuvaPaneli;
    // End of variables declaration//GEN-END:variables

    private void aloitaPeli(Tehtavatehdas peli) {
        pelipaneli = new Pelipaneli(new Pelikuuntelija() {

            @Override
            public void peliPaattyi() {
                naytaValinta();
            }
        }, peli);
        vaihdaPaneli(pelipaneli);
        pelipaneli.aktivoi();
    }

    public void valintaTehty(Pelivalinta valinta) {
        valintaPaneli.deaktivoi();
        aloitaPeli(valinta.peli);
    }

    private void naytaValinta() {
        vaihdaPaneli(valintaPaneli);
        valintaPaneli.aktivoi();
    }

    private void vaihdaPaneli(JComponent paneli) {
        vaihtuvaPaneli.removeAll();
        vaihtuvaPaneli.add(paneli, BorderLayout.CENTER);
        vaihtuvaPaneli.revalidate();
    }

    private void naytaVirhe(String virhe, Throwable t) {
        JOptionPane.showMessageDialog(this, virhe, "Virhe",
                JOptionPane.ERROR_MESSAGE);
    }

    private static class Pelivalinta<T> implements Valinta {

        private final String otsikko;
        private final String selite;
        private final Tehtavatehdas peli;

        public Pelivalinta(String otsikko, String selite,
                Tehtavatehdas peli) {
            this.otsikko = otsikko;
            this.selite = selite;
            this.peli = peli;
        }

        @Override
        public String annaOtsikko() {
            return otsikko;
        }

        @Override
        public String annaSelite() {
            return selite;
        }
        
    }

}
