/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laskarit.ui;

import laskarit.tehtavat.KaikkiTehtavat;
import laskarit.tehtavat.Kertolaskarit;
import laskarit.tehtavat.Tehtava;
import laskarit.tehtavat.Tehtavatehdas;
import laskarit.tehtavat.Yhteenlaskarit;

/**
 *
 * @author simo
 */
public class PeliIkkuna extends javax.swing.JFrame {
    private Pelipaneli pelipaneli;

    private Tehtavatehdas tehtavat;
    private Tehtava tehtava;

    /**
     * Creates new form PeliIkkuna
     */
    public PeliIkkuna() {
        initComponents();
        aloitaPeli(new Yhteenlaskarit(10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vaihtuvaPaneli = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuPeli = new javax.swing.JMenu();
        menuItemLopeta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laskarit");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));
        getContentPane().add(vaihtuvaPaneli);

        menuPeli.setText("Peli");

        menuItemLopeta.setText("Lopeta");
        menuItemLopeta.setToolTipText("");
        menuItemLopeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLopetaActionPerformed(evt);
            }
        });
        menuPeli.add(menuItemLopeta);

        menuBar.add(menuPeli);

        setJMenuBar(menuBar);

        setBounds(0, 0, 532, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemLopetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLopetaActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_menuItemLopetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeliIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeliIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeliIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeliIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeliIkkuna().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemLopeta;
    private javax.swing.JMenu menuPeli;
    private javax.swing.JPanel vaihtuvaPaneli;
    // End of variables declaration//GEN-END:variables

    private void aloitaPeli(Tehtavatehdas peli) {
        vaihtuvaPaneli.removeAll();
        pelipaneli = new Pelipaneli(this, peli);
        vaihtuvaPaneli.add(pelipaneli);
    }

}
