/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laskarit.ui;

import laskarit.muotoilu.Esitys;

/**
 *
 * @author simo
 */
public class Pelipaneli extends javax.swing.JPanel {

    PeliIkkuna ikkuna;

    /**
     * Creates new form Pelipaneli
     */
    public Pelipaneli(PeliIkkuna ikkuna) {
        this.ikkuna = ikkuna;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        kysymyspaneli = new javax.swing.JPanel();
        labelKysymys = new javax.swing.JLabel();
        panelVaaraVastaus = new javax.swing.JPanel();
        labelVaaraVastaus = new javax.swing.JLabel();
        vastauspaneli = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel1 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        tfVastaus = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
        add(filler1);

        kysymyspaneli.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        kysymyspaneli.setLayout(new javax.swing.BoxLayout(kysymyspaneli, javax.swing.BoxLayout.LINE_AXIS));

        labelKysymys.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelKysymys.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKysymys.setText("kysymys");
        labelKysymys.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        kysymyspaneli.add(labelKysymys);

        add(kysymyspaneli);

        panelVaaraVastaus.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        panelVaaraVastaus.setMinimumSize(new java.awt.Dimension(115, 50));
        panelVaaraVastaus.setName(""); // NOI18N
        panelVaaraVastaus.setPreferredSize(new java.awt.Dimension(400, 50));
        panelVaaraVastaus.setLayout(new javax.swing.BoxLayout(panelVaaraVastaus, javax.swing.BoxLayout.LINE_AXIS));

        labelVaaraVastaus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelVaaraVastaus.setForeground(javax.swing.UIManager.getDefaults().getColor("nb.errorForeground"));
        labelVaaraVastaus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVaaraVastaus.setText("Väärä vastaus!");
        labelVaaraVastaus.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        labelVaaraVastaus.setPreferredSize(null);
        panelVaaraVastaus.add(labelVaaraVastaus);

        add(panelVaaraVastaus);

        vastauspaneli.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 1, 2, 1));
        vastauspaneli.setMinimumSize(new java.awt.Dimension(150, 25));
        vastauspaneli.setLayout(new javax.swing.BoxLayout(vastauspaneli, javax.swing.BoxLayout.LINE_AXIS));
        vastauspaneli.add(filler3);

        jLabel1.setLabelFor(tfVastaus);
        jLabel1.setText("Vastaus");
        vastauspaneli.add(jLabel1);
        vastauspaneli.add(filler4);

        tfVastaus.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfVastaus.setMaximumSize(new java.awt.Dimension(100, 40));
        tfVastaus.setMinimumSize(new java.awt.Dimension(100, 20));
        tfVastaus.setPreferredSize(new java.awt.Dimension(100, 30));
        tfVastaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVastausActionPerformed(evt);
            }
        });
        vastauspaneli.add(tfVastaus);
        vastauspaneli.add(filler2);

        add(vastauspaneli);
    }// </editor-fold>//GEN-END:initComponents

    private void tfVastausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVastausActionPerformed
        String vastaus = tfVastaus.getText();
        tfVastaus.setText("");
        ikkuna.vastausAnnettu(vastaus);
    }//GEN-LAST:event_tfVastausActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel kysymyspaneli;
    private javax.swing.JLabel labelKysymys;
    private javax.swing.JLabel labelVaaraVastaus;
    private javax.swing.JPanel panelVaaraVastaus;
    private javax.swing.JTextField tfVastaus;
    private javax.swing.JPanel vastauspaneli;
    // End of variables declaration//GEN-END:variables

    void uusiKysymys(Esitys kysymys) {
        labelVaaraVastaus.setVisible(false);
        labelKysymys.setText("<html>" + kysymys.toString(null) + "</html>");
    }

    void vaaraVastaus() {
        labelVaaraVastaus.setVisible(true);
    }
}
